import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import SideBar from "@/components/layout/side-bar";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} text-white bg-[#0F100F] relative overflow-auto`}
      >
        <div className="h-full w-full absolute top-0 left-0 overflow-hidden">
          <div className="relative">
            <div className="w-[150vw] h-[150vw] rounded-full bg-primary opacity-40 blur-[120px] absolute top-[600px] -left-[100vw] -z-10"></div>
          </div>
        </div>
        <Header />
        <div className="flex gap-10 px-4 lg:px-10 py-20 items-start">
          <div className="hidden md:block">
            <SideBar />
          </div>
          <main className="w-0 grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
